name: ci

on:
  push:
    branches:
      - master
      - dev
  pull_request: {}

permissions:
  contents: read

jobs:
  vet-test-vuln:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test ./...

      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
